### PR TITLE
Bump version to 2.26.1

### PR DESCRIPTION
**Pull request by petersmythe**

### CODE REVIEW

**Comment by petersmythe** [comment]
Could I request commit access to this repo, please?

**Comment by buehner** [comment]
I think @jodygarnett could help here as I don't have the permissions.

**Comment by jodygarnett** [comment]
What is up?

**Comment by buehner** [comment]
> Could I request commit access to this repo, please?

@jodygarnett  Can you give commit access to @petersmythe ?

**Pull request merged**
