### PR TITLE
chore: use latest gs everywhere

### PR DESCRIPTION
**Pull request by buehner**
Just updating to latest GeoServer as default. Also updates doc.

### CODE REVIEW

**Comment by reinout** [comment]
Shouldn't this be `2.26.0`?

**Comment by buehner** [comment]
> Shouldn't this be `2.26.0`?

As 2.26.0 is not yet released, the documented steps would not work currently (docker pull etc). But once 2.26.0 is released, we should update again. Would be great to have some kind of automatization for this in future.

In my eyes theses changes are more "pro forma" as you can always use the build argument for the gs version you like to build. But of course it makes sense to have it up-to-date.

**Comment by reinout** [comment]
2.26.0 isn't released yet? Why is there a (failing, but that's known) 2.26.0 geoserver docker release then? I assumed that a docker release would only be made from a released geoserver version.

If my assumption is wrong, I have to change my own renovatebot setup, as it happily picked up the 2.26.0. But if the geoserver docker release is made before there's an actual release: that's not what was done up till now (as far as I could see).

**Comment by buehner** [comment]
Ahh, interesting. I did not know that. Just had a look at https://geoserver.org/download/

So I guess the release process i currently ongoing...

**Pull request merged**
