### PR TITLE
Version 2.22.0 in docker compose and readme

### PR DESCRIPTION
**Pull request by herrapa**
Keep geoserver version in Docker compose demo file and readme in sync with Dockerfile

### CODE REVIEW

**Comment by JakobMiksch** [comment]
Good catch. The version `2.22.0` is not published on the registry yet: https://docker.osgeo.org/#browse/browse:geoserver-docker:v2%2Fgeoserver%2Ftags
Ideally the PR will be merged afterwards

**Comment by buehner** [comment]
Yes. I can wait with merging until 2.22.0 is published

**Comment by weskamm** [comment]
I think we should change the docs to use `latest` tag instead of fixing version numbers after every release.
But before that, we need the latest tag, as it currently does not exist yet

**Comment by buehner** [comment]
I will merge now as 2.22.0 is available: https://docker.osgeo.org/#browse/browse:geoserver-docker:v2%2Fgeoserver%2Ftags%2F2.22.0

**Pull request merged**
